name: atsh.me
description: My blag which I post on
url: http://atsh.me
exclude: [CNAME, config.rb, .gitignore, Gemfile, package.json, package-lock.json, node_modules, postcss.config.js, style]
permalink: /blog/:title
